export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: "./images/art.png",
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build yor brand",
    img: "./images/logo.jpg",
  },
  {
    id: 3,
    title: "WordPress",
    desc: "Customize your site",
    img: "./images/word.jpg",
  },
  {
    id: 4,
    title: "Voice Over",
    desc: "Share your message",
    img: "./images/voice.jpg",
  },
  {
    id: 5,
    title: "Video Explainer",
    desc: "Engage your audience",
    img: "./images/vid.jpg",
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Reach more customers",
    img: "./images/social.webp",
  },
  {
    id: 7,
    title: "SEO",
    desc: "Unlock growth online",
    img: "./images/nature.jpg",
  },
  {
    id: 8,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/vs.webp",
  },
  {
    id: 9,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/vs.webp",
  },
  {
    id: 10,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/ai.webp",
  },
  {
    id: 11,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/vs.webp",
  },
  {
    id: 12,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/vs.webp",
  },
  {
    id: 13,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/vs.webp",
  },
  {
    id: 14,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/study.png",
  },
  {
    id: 15,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./images/vs.webp",
  },
];

export const projects = [
  {
    id: 1,
    img: "./images/web.jpg",
    pp: "./images/girl.png",
    cat: "Web and Mobile Design",
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "./images/logo.jpg",
    pp: "./images/Avtar.jpg",
    cat: "Logo Design",
    username: "Morton Green",
  },
  {
    id: 3,
    img: "./images/animated.webp",
    pp: "./images/girl.png",
    cat: "Animated GIFs",
    username: "Emmett Potter",
  },
  {
    id: 4,
    img: "./images/nature.jpg",
    pp: "./images/Avtar.jpg",
    cat: "Packaging Design",
    username: "Ethan",
  },
  {
    id: 5,
    img: "./images/vs.webp",
    pp: "./images/girl.png",
    cat: "Social Media Design",
    username: "Emma",
  },
  {
    id: 6,
    img: "./images/nature.jpg",
    pp: "./images/Avtar.jpg",
    cat: "Illustration",
    username: "Benjamin",
  },
  {
    id: 7,
    img: "./images/vs.webp",
    pp: "./images/girl.png",
    cat: "Book Design",
    username: "Hannah",
  },
  {
    id: 8,
    img: ".images/mar.webp",
    pp: "./images/Avtar.jpg",
    cat: "Digital Marketing",
    username: "Lucas",
  },
];

export const gigs = [
  {
    id: 1,
    img: "./images/nature.jpg",
    pp: "./images/girl.png",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anna Bell",
  },
  {
    id: 2,
    img: "./images/vs.webp",
    pp: "./images/Avtar.jpg",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Lannie Coleman",
  },
  {
    id: 3,
    img: "./images/sq.jpg",
    pp: "./images/girl.png",
    desc: "I will creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Carol Steve",
  },
  {
    id: 4,
    img: "./images/rb.jpg",
    pp: "./images/Avtar.jpg",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Don Weber",
  },
  {
    id: 5,
    img: "./images/study.png",
    pp: "./images/girl.png",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Audrey Richards",
  },
  {
    id: 6,
    img: "./images/dr.jpeg",
    pp: "./images/Avtar.jpg",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Walton Shepard ",
  },
  {
    id: 7,
    img: "./images/vs.webp",
    pp: "./images/girl.png",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Waverly Schaefer",
  },
  {
    id: 8,
    img: "./images/ai.webp",
    pp: "./images/Avtar.jpg",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Wilton Hunt",
  },
];

export const vPro = [
  {
    id: 1,
    vid: "",
    name: "S&K",
    company: "ABC",
    quote: `"When you want to create a business bigger than yourself, you need a lot of help. That's what Connect does."`,
  },
  {
    id: 2,
    vid: "",
    name: "S&K",
    company: "ABC",
    quote: `"When you want to create a business bigger than yourself, you need a lot of help. That's what Connect does."`,
  },
  {
    id: 3,
    vid: "",
    name: "S&K",
    company: "ABC",
    quote: `"When you want to create a business bigger than yourself, you need a lot of help. That's what Connect does."`,
  },
  {
    id: 4,
    vid: "",
    name: "S&K",
    company: "ABC",
    quote: `"When you want to create a business bigger than yourself, you need a lot of help. That's what Connect does."`,
  },
  {
    id: 5,
    vid: "",
    name: "S&K",
    company: "ABC",
    quote: `"When you want to create a business bigger than yourself, you need a lot of help. That's what Connect does."`,
  },
  {
    id: 6,
    vid: "",
    name: "S&K",
    company: "ABC",
    quote: `"When you want to create a business bigger than yourself, you need a lot of help. That's what Connect does."`,
  },
];
